# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "e2b220ec1d2ac4e75a943f386fddcdda"
application_url = "https://meanwhile-carrying-artistic-ment.trycloudflare.com"
embedded = true
name = "boa-hame-task-Sh"
handle = "boa-hame-task-sh"

[build]
include_config_on_deploy = true
dev_store_url = "home-assignment-226.myshopify.com"
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2024-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://meanwhile-carrying-artistic-ment.trycloudflare.com/auth/callback",
  "https://meanwhile-carrying-artistic-ment.trycloudflare.com/auth/shopify/callback",
  "https://meanwhile-carrying-artistic-ment.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
